define([], function () {
  return {
    businessInfo: [{
      label: '付款单位：',
      value: '国网四川省电力公司本部财务'
    }, {
      label: '付款账号：',
      value: '1602022101276101'
    }, {
      label: '付款开户金融机构：',
      value: '中电财'
    }, {
      label: '支付金额：',
      value: '5,400.55'
    }, {
      label: '收款单位：',
      value: '国电成都金堂发电有限公司'
    }, {
      label: '收款账号：',
      value: '4402241019000027069'
    }, {
      label: '收款开户金融机构：',
      value: '中国工商银行股份有限公司四川省成都市龙舟路支行'
    }, {
      label: '支付内容：',
      value: 'FDl4_金堂62#61#11月2'
    }, {
      label: '支付时间：',
      value: '2018-01-16 15:46:07'
    }],
    dealPersons: [{
      name: 'xiaodong',
      phone: '123456789',
      duty: 'kaifa',
      selected: true
    }, {
      name: 'jiaoyan',
      phone: '15674566465',
      duty: 'zixun'
    }],
    feedbackListNames: {
      '0': '非风险',
      '1': '整改中',
      '2': '已整改',
      '3': '不可整改'
    },
    feedbackList: [{
      title: '非风险',
      value: 0
    }, {
      title: '整改中',
      value: 1
    }, {
      title: '已整改',
      value: 2
    }, {
      title: '不可整改',
      value: 3
    }],
    // 风险单位校验id
    fxdwVerifyid: '1001',
    // 二级财务校验id
    ejcwVerifyid: '1002',
    // 运监可发起督办的岗位
    verifyIsYjLaunchIds: ['1003', '1004', '1005', '1006', '1007'],
    // 非运监可发起督办的岗位
    verifyNotYjLaunchIds: ['1001', '1002', '1003', '1007'],
    // 非运监控情况下只保留风险单位、二级财务、总部财务的意见即可，其他四项隐藏或者置灰
    fyjPosition: ['1001', '1002', '1003'],
    // 运监roleids
    yjVerifyIds: ['1004', '1005', '1006'],
    // 审核意见
    auditSituation: [{
      label: '风险单位',
      field: 'finlev3',
      alias: 'sh6',
      roleField: '1001',
      roleid: '',
      serial: 6,
      value: 4,
      valTitle: '',
    }, {
      label: '二级财务',
      field: 'finlev2',
      alias: 'sh5',
      roleField: '1002',
      roleid: '',
      serial: 5,
      value: 4,
      valTitle: '',
    }, {
      label: '总部财务',
      field: 'finlev1',
      alias: 'sh4',
      roleField: '1003',
      roleid: '',
      serial: 4,
      value: 4,
      valTitle: '',
    }, {
      label: '三级运监',
      field: 'pmlev3',
      alias: 'sh3',
      roleField: '1004',
      roleid: '',
      serial: 3,
      value: 4,
      valTitle: '',
    }, {
      label: '二级运监',
      field: 'pmlev2',
      alias: 'sh2',
      roleField: '1005',
      roleid: '',
      serial: 2,
      value: 4,
      valTitle: '',
    }, {
      label: '总部运监',
      field: 'pmlev1',
      alias: 'sh1',
      roleField: '1006',
      roleid: '',
      serial: 1,
      value: 4,
      valTitle: '',
    }, {
      label: '海投',
      field: 'abordnote',
      alias: 'sh7',
      roleField: '1007',
      roleid: '',
      serial: 7,
      value: 4,
      valTitle: '',
    }],
    // 反馈意见
    feedbackSituation: [{
      label: '风险单位',
      field: 'finlev3',
      alias: 'fk6',
      roleField: '1001',
      roleid: '',
      serial: 6,
      value: 4,
      valTitle: '',
    }, {
      label: '二级财务',
      field: 'finlev2',
      alias: 'fk5',
      roleField: '1002',
      roleid: '',
      serial: 5,
      value: 4,
      valTitle: '',
    }, {
      label: '总部财务',
      field: 'finlev1',
      alias: 'fk4',
      roleField: '1003',
      roleid: '',
      serial: 4,
      value: 4,
      valTitle: '',
    }, {
      label: '三级运监',
      field: 'pmlev3',
      alias: 'fk3',
      roleField: '1004',
      roleid: '',
      serial: 3,
      value: 4,
      valTitle: '',
    }, {
      label: '二级运监',
      field: 'pmlev2',
      alias: 'fk2',
      roleField: '1005',
      roleid: '',
      serial: 2,
      value: 4,
      valTitle: '',
    }, {
      label: '总部运监',
      field: 'pmlev1',
      alias: 'fk1',
      roleField: '1006',
      roleid: '',
      serial: 1,
      value: 4,
      valTitle: '',
    }, {
      label: '海投',
      field: 'abordnote',
      alias: 'fk7',
      roleField: '1007',
      roleid: '',
      serial: 7,
      value: 4,
      valTitle: '',
    }],
    fkqkNames: { // 反馈历史名称
      1: '总部运监',
      2: '二级运监',
      3: '三级运监',
      4: '总部财务',
      5: '二级财务',
      6: '风险单位',
      7: '海投'
    },
    // 风险等级样式
    fxdjClass: {
      '1': 'red',
      '2': 'orange',
      '4': 'yellow',
      '0': 'green',
    },
    // 风险等级文本
    fxdjText: {
      '1': '一级',
      '2': '二级',
      '4': '三级',
      '0': '非风险',
    },
    // 督办单据状态样式
    dbdjStatusClass: {
      '1': 'non-launch',
      '4': 'to-examine',
      '2': 'to-feedback',
      '32': 'non-risk',
      '8': 'sys-close',
      '16': 'dbdj-close'
    },
    // 督办单据状态文本
    dbdjStatusText: {
      '1': '未发起',
      '4': '待审核',
      '2': '待反馈',
      '32': '非风险',
      '8': '系统关闭',
      '16': '督办关闭'
    },
  }
});